//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeliveryEntities : DbContext
    {
        public DeliveryEntities()
            : base("name=DeliveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucNang> ChucNangs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanChucNang> PhanChucNangs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<TrangThaiDonHang> TrangThaiDonHangs { get; set; }
    
        public virtual ObjectResult<LayChucNang_Result> LayChucNang(Nullable<int> maNhanVien)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("MaNhanVien", maNhanVien) :
                new ObjectParameter("MaNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayChucNang_Result>("LayChucNang", maNhanVienParameter);
        }
    
        public virtual ObjectResult<getDonHang_ChuaNhan_Result> getDonHang_ChuaNhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDonHang_ChuaNhan_Result>("getDonHang_ChuaNhan");
        }
    
        public virtual ObjectResult<getDonHang_DaNhan_Result> getDonHang_DaNhan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDonHang_DaNhan_Result>("getDonHang_DaNhan");
        }
    
        public virtual int XacNhan_DonHang_ChuaNhan(Nullable<int> maDH)
        {
            var maDHParameter = maDH.HasValue ?
                new ObjectParameter("MaDH", maDH) :
                new ObjectParameter("MaDH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XacNhan_DonHang_ChuaNhan", maDHParameter);
        }
    }
}
