//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DH_DaNhan
    {
        public int MaDH_DaNhan { get; set; }
        public Nullable<int> MaDH { get; set; }
        public string MaVanDon { get; set; }
        public string HoTenNG { get; set; }
        public string DiaChiNG { get; set; }
        public string SdtNG { get; set; }
        public string HotenNN { get; set; }
        public string DiaChiNN { get; set; }
        public string SdtNN { get; set; }
        public string TrangThai { get; set; }
    }
}
