//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDonHang { get; set; }
        public string Tu { get; set; }
        public string NguoiGui { get; set; }
        public string Den { get; set; }
        public string NguoiNhan { get; set; }
        public string Sdt { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string SdtNguoiGui { get; set; }
    
        public virtual TrangThaiDonHang TrangThaiDonHang { get; set; }
        public virtual NhanDon NhanDon { get; set; }
    }
}
