//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangCanVanChuyen
    {
        public int MaVanDon { get; set; }
        public Nullable<int> MaDonHang { get; set; }
        public Nullable<int> NhanVienVanChuyen { get; set; }
        public Nullable<double> PhiVanChuyen { get; set; }
    
        public virtual PhanPhoi PhanPhoi { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
