//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int MaDH { get; set; }
        public int MaVanDon { get; set; }
        public string HoTenNG { get; set; }
        public string DiaChiNG { get; set; }
        public string SdtNG { get; set; }
        public string HoTenNN { get; set; }
        public string DiaChiNN { get; set; }
        public string SdtNN { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
    
        public virtual TrangThaiDonHang TrangThaiDonHang { get; set; }
    }
}
