

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Delivery.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class GiaoHangEntities : DbContext
{
    public GiaoHangEntities()
        : base("name=GiaoHangEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ChucNang> ChucNangs { get; set; }

    public virtual DbSet<ChucVu> ChucVus { get; set; }

    public virtual DbSet<DonHang> DonHangs { get; set; }

    public virtual DbSet<DonHangCanVanChuyen> DonHangCanVanChuyens { get; set; }

    public virtual DbSet<KhuVuc> KhuVucs { get; set; }

    public virtual DbSet<NhanDon> NhanDons { get; set; }

    public virtual DbSet<NhanVien> NhanViens { get; set; }

    public virtual DbSet<PhanPhoi> PhanPhois { get; set; }

    public virtual DbSet<Quyen> Quyens { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }

    public virtual DbSet<TrangThaiDonHang> TrangThaiDonHangs { get; set; }


    public virtual ObjectResult<MenuOf_Result> MenuOf(Nullable<int> maNhanVien)
    {

        var maNhanVienParameter = maNhanVien.HasValue ?
            new ObjectParameter("MaNhanVien", maNhanVien) :
            new ObjectParameter("MaNhanVien", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuOf_Result>("MenuOf", maNhanVienParameter);
    }


    public virtual ObjectResult<NhanVien_ChiTiet_Result> NhanVien_ChiTiet(Nullable<int> maNhanVien)
    {

        var maNhanVienParameter = maNhanVien.HasValue ?
            new ObjectParameter("MaNhanVien", maNhanVien) :
            new ObjectParameter("MaNhanVien", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVien_ChiTiet_Result>("NhanVien_ChiTiet", maNhanVienParameter);
    }


    public virtual ObjectResult<NhanVien_DanhSach_Result> NhanVien_DanhSach()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVien_DanhSach_Result>("NhanVien_DanhSach");
    }


    public virtual ObjectResult<Nullable<int>> NhanVien_Sua(Nullable<int> maNhanVien, string tenNhanVien, Nullable<System.DateTime> ngaySinh, string email, string soDienThoai, byte[] anhDaiDien, Nullable<int> chucVu)
    {

        var maNhanVienParameter = maNhanVien.HasValue ?
            new ObjectParameter("MaNhanVien", maNhanVien) :
            new ObjectParameter("MaNhanVien", typeof(int));


        var tenNhanVienParameter = tenNhanVien != null ?
            new ObjectParameter("TenNhanVien", tenNhanVien) :
            new ObjectParameter("TenNhanVien", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var soDienThoaiParameter = soDienThoai != null ?
            new ObjectParameter("SoDienThoai", soDienThoai) :
            new ObjectParameter("SoDienThoai", typeof(string));


        var anhDaiDienParameter = anhDaiDien != null ?
            new ObjectParameter("AnhDaiDien", anhDaiDien) :
            new ObjectParameter("AnhDaiDien", typeof(byte[]));


        var chucVuParameter = chucVu.HasValue ?
            new ObjectParameter("ChucVu", chucVu) :
            new ObjectParameter("ChucVu", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NhanVien_Sua", maNhanVienParameter, tenNhanVienParameter, ngaySinhParameter, emailParameter, soDienThoaiParameter, anhDaiDienParameter, chucVuParameter);
    }


    public virtual ObjectResult<Nullable<decimal>> NhanVien_Them(string tenNhanVien, Nullable<System.DateTime> ngaySinh, string email, string soDienThoai, byte[] anhDaiDien, Nullable<int> chucVu)
    {

        var tenNhanVienParameter = tenNhanVien != null ?
            new ObjectParameter("TenNhanVien", tenNhanVien) :
            new ObjectParameter("TenNhanVien", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var soDienThoaiParameter = soDienThoai != null ?
            new ObjectParameter("SoDienThoai", soDienThoai) :
            new ObjectParameter("SoDienThoai", typeof(string));


        var anhDaiDienParameter = anhDaiDien != null ?
            new ObjectParameter("AnhDaiDien", anhDaiDien) :
            new ObjectParameter("AnhDaiDien", typeof(byte[]));


        var chucVuParameter = chucVu.HasValue ?
            new ObjectParameter("ChucVu", chucVu) :
            new ObjectParameter("ChucVu", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("NhanVien_Them", tenNhanVienParameter, ngaySinhParameter, emailParameter, soDienThoaiParameter, anhDaiDienParameter, chucVuParameter);
    }


    public virtual ObjectResult<Nullable<int>> NhanVien_Xoa(Nullable<int> maNhanVien)
    {

        var maNhanVienParameter = maNhanVien.HasValue ?
            new ObjectParameter("MaNhanVien", maNhanVien) :
            new ObjectParameter("MaNhanVien", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NhanVien_Xoa", maNhanVienParameter);
    }


    public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));


        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }


    public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));


        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }


    public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
    }


    public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
    }


    public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
    }


    public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
    {

        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));


        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));


        var new_diagramnameParameter = new_diagramname != null ?
            new ObjectParameter("new_diagramname", new_diagramname) :
            new ObjectParameter("new_diagramname", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
    }


    public virtual int sp_upgraddiagrams()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
    }


    public virtual ObjectResult<TaiKhoan_DangNhap_Result> TaiKhoan_DangNhap(string tenTaiKhoan)
    {

        var tenTaiKhoanParameter = tenTaiKhoan != null ?
            new ObjectParameter("TenTaiKhoan", tenTaiKhoan) :
            new ObjectParameter("TenTaiKhoan", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoan_DangNhap_Result>("TaiKhoan_DangNhap", tenTaiKhoanParameter);
    }


    public virtual ObjectResult<string> TaiKhoan_LayMatKhau(string tenTaiKhoan)
    {

        var tenTaiKhoanParameter = tenTaiKhoan != null ?
            new ObjectParameter("TenTaiKhoan", tenTaiKhoan) :
            new ObjectParameter("TenTaiKhoan", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TaiKhoan_LayMatKhau", tenTaiKhoanParameter);
    }


    public virtual int ResetPass(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ResetPass", idParameter);
    }


    public virtual ObjectResult<SelectNV_Result> SelectNV()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNV_Result>("SelectNV");
    }


    public virtual ObjectResult<SelectRole_Result> SelectRole()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectRole_Result>("SelectRole");
    }


    public virtual ObjectResult<TaiKhoan_DanhSach_Result> TaiKhoan_DanhSach()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoan_DanhSach_Result>("TaiKhoan_DanhSach");
    }


    public virtual ObjectResult<string> TaiKhoan_Them(string username, string password, Nullable<int> maNV)
    {

        var usernameParameter = username != null ?
            new ObjectParameter("Username", username) :
            new ObjectParameter("Username", typeof(string));


        var passwordParameter = password != null ?
            new ObjectParameter("Password", password) :
            new ObjectParameter("Password", typeof(string));


        var maNVParameter = maNV.HasValue ?
            new ObjectParameter("MaNV", maNV) :
            new ObjectParameter("MaNV", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TaiKhoan_Them", usernameParameter, passwordParameter, maNVParameter);
    }


    public virtual ObjectResult<SelectCV_Result> SelectCV()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCV_Result>("SelectCV");
    }


    public virtual ObjectResult<Nullable<int>> TaiKhoan_LayID(Nullable<int> manv)
    {

        var manvParameter = manv.HasValue ?
            new ObjectParameter("manv", manv) :
            new ObjectParameter("manv", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TaiKhoan_LayID", manvParameter);
    }


    public virtual ObjectResult<Profile_Get_Result> Profile_Get(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("Id", id) :
            new ObjectParameter("Id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Profile_Get_Result>("Profile_Get", idParameter);
    }


    public virtual ObjectResult<Nullable<int>> Profile_Sua(Nullable<int> maNhanVien, string tenNhanVien, Nullable<System.DateTime> ngaySinh, string email, string soDienThoai, byte[] anhDaiDien)
    {

        var maNhanVienParameter = maNhanVien.HasValue ?
            new ObjectParameter("MaNhanVien", maNhanVien) :
            new ObjectParameter("MaNhanVien", typeof(int));


        var tenNhanVienParameter = tenNhanVien != null ?
            new ObjectParameter("TenNhanVien", tenNhanVien) :
            new ObjectParameter("TenNhanVien", typeof(string));


        var ngaySinhParameter = ngaySinh.HasValue ?
            new ObjectParameter("NgaySinh", ngaySinh) :
            new ObjectParameter("NgaySinh", typeof(System.DateTime));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var soDienThoaiParameter = soDienThoai != null ?
            new ObjectParameter("SoDienThoai", soDienThoai) :
            new ObjectParameter("SoDienThoai", typeof(string));


        var anhDaiDienParameter = anhDaiDien != null ?
            new ObjectParameter("AnhDaiDien", anhDaiDien) :
            new ObjectParameter("AnhDaiDien", typeof(byte[]));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Profile_Sua", maNhanVienParameter, tenNhanVienParameter, ngaySinhParameter, emailParameter, soDienThoaiParameter, anhDaiDienParameter);
    }


    public virtual ObjectResult<TaiKhoan_DoiMK_Result> TaiKhoan_DoiMK(Nullable<int> maNhanVien, string matKhau)
    {

        var maNhanVienParameter = maNhanVien.HasValue ?
            new ObjectParameter("MaNhanVien", maNhanVien) :
            new ObjectParameter("MaNhanVien", typeof(int));


        var matKhauParameter = matKhau != null ?
            new ObjectParameter("MatKhau", matKhau) :
            new ObjectParameter("MatKhau", typeof(string));

        
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoan_DoiMK_Result>("TaiKhoan_DoiMK", maNhanVienParameter, matKhauParameter);
    }


    public virtual ObjectResult<TaiKhoan_Profile_Result> TaiKhoan_Profile(Nullable<int> maNhanVien)
    {

        var maNhanVienParameter = maNhanVien.HasValue ?
            new ObjectParameter("MaNhanVien", maNhanVien) :
            new ObjectParameter("MaNhanVien", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoan_Profile_Result>("TaiKhoan_Profile", maNhanVienParameter);
    }

}

}

