
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Delivery.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NhanDon
{

    public int MaDonHang { get; set; }

    public Nullable<int> NhanVienThucHien { get; set; }

    public Nullable<System.DateTime> ThoiGianNhan { get; set; }



    public virtual DonHang DonHang { get; set; }

    public virtual NhanVien NhanVien { get; set; }

    public virtual PhanPhoi PhanPhoi { get; set; }

}

}
