//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaPhanQuyen { get; set; }
        public Nullable<int> MaQuyen { get; set; }
        public Nullable<int> MaChucVu { get; set; }
    }
}
