//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chức_năng
    {
        public int Mã_chức_năng { get; set; }
        public string Tên_chức_năng { get; set; }
        public string Biểu_tượng { get; set; }
    }
}
