//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhân_viên
    {
        public int Mã_nhân_viên { get; set; }
        public string Tên_nhân_viên { get; set; }
        public Nullable<int> Mã_chức_vụ { get; set; }
    
        public virtual Tài_khoản Tài_khoản { get; set; }
    }
}
