//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phân_quyền
    {
        public int Mã_phân_quyền { get; set; }
        public Nullable<int> Mã_quyền { get; set; }
        public Nullable<int> Mã_chức_vụ { get; set; }
    }
}
