//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tài_khoản
    {
        public int Mã_nhân_viên { get; set; }
        public string Tài_khoản1 { get; set; }
        public string Mật_khẩu { get; set; }
    
        public virtual Nhân_viên Nhân_viên { get; set; }
    }
}
